version: '3.7'
services:
  cassandra:
    image: cassandra:3.11.5
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - ./build/libs/cassandra-trigger-1.0.jar:/etc/cassandra/triggers/cassandra-trigger-1.0.jar

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
    - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.2
    ports:
    - "9092:9092"
    depends_on:
    - zookeeper
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test-topic:1:1"
